Шаблонизация проекта
htmlacademy-php/1518675-readme-12 pull request #5
Opened 2021-10-20 11:21 UTC by gladosq

---
:mortar_board: [Шаблонизация проекта](https://up.htmlacademy.ru/php/12/user/1518675/tasks/7)

2021-10-21 06:25 UTC, ademaro commented on schema.sql
> +
`use readme;` — что бы не указывать название БД каждый раз

2021-10-21 06:27 UTC, ademaro commented on schema.sql
> +	content_id INT,
почему не post_id?

2021-10-21 06:27 UTC, ademaro commented on schema.sql
> +	autor_id INT,
user_id?

2021-10-21 06:29 UTC, ademaro commented on schema.sql
> +	content TEXT(1000),
TEXT можем не ограничивать

2021-10-21 06:30 UTC, ademaro requested changes
Давай немного подправим и двинем дальше! В целом — всё круто, молодец

2021-10-25 17:37 UTC, gladosq commented on schema.sql
> +	content TEXT(1000),
Без ограничений крашится

2021-10-29 04:35 UTC, ademaro commented on schema.sql
> +	content VARCHAR(128),
а почему контент так урезали? больше 128 не может быть?

2021-10-29 04:36 UTC, ademaro commented on schema.sql
> +	FOREIGN KEY (user_id) REFERENCES readme.users (id),
тут так же можно убрать `readme.`

2021-10-29 04:38 UTC, ademaro commented on schema.sql
> +	hashtag INT,
хэштеги — это m2m (многие-ко-многим), как ты укажешь несколько хэштегов в посте?) посмотри как реализовать m2m (сразу направлю — через вспомогательную таблицу)

2021-10-29 05:53 UTC, ademaro requested changes
Жду поправок тогда

2021-11-02 15:40 UTC, ademaro commented on schema.sql
> +	autor_q VARCHAR(128),
что за сокращение q? и author правильно)

2021-11-02 15:46 UTC, ademaro commented on schema.sql
> +	hashtag INT,
ну надо доделать хэштеги, так и не понял — ты разобрался как реализовал но забыл или непонятно вообще?

2021-11-02 15:47 UTC, ademaro commented on schema.sql
> +	hashtag INT,
а, вижу, ток надо было назвать тогда уж hashtag_id

2021-11-02 15:50 UTC, ademaro approved these changes
Давай двинемся дальше, что бы не было ощущения, что стоим на месте, но надо будет подправить моменты... Жду отдельным коммитом в следующем задании

2021-11-02 15:50 UTC, merged